#NumPy学习笔记

In [1]:
# 导入NumPy
import numpy as np

# 创建二维数组
a = np.arange(15).reshape(3, 5)
print type(a)
a

<type 'numpy.ndarray'>


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
print 'a.shape=', a.shape
print 'a.ndim=', a.ndim     # 几维
print 'a.dtype=', a.dtype
print 'a.dtype.name=', a.dtype.name
print 'a.itemsize=', a.itemsize     # 每个元素的字节大小
print 'a.size=', a.size

a.shape= (3L, 5L)
a.ndim= 2
a.dtype= int32
a.dtype.name= int32
a.itemsize= 4
a.size= 15


In [15]:
a1 = np.array([2, 3, 4])
a2 = np.array([2, 3, 4] * 4)
a1, \
a2

(array([2, 3, 4]), array([2, 3, 4, 2, 3, 4, 2, 3, 4, 2, 3, 4]))

In [4]:
# 随机数
rd = np.random.randint(1, 100, 20)  # 整数
rd

array([89, 22, 23, 28, 74, 16,  4, 61, 31, 19, 62, 93, 52, 15, 90, 91,  5,
       36,  1, 65])

In [6]:
rd1 = np.random.randn(5, 2, 3)
rd1

array([[[ 0.89829838,  0.6875708 ,  1.37188193],
        [ 0.15626574, -0.09271864, -0.57698472]],

       [[-1.65221809, -0.35853338,  0.24514813],
        [-1.72656118, -0.06079837, -0.27696511]],

       [[-0.07831238,  1.2778987 , -0.4639187 ],
        [-1.20477055,  1.03501582,  0.12196425]],

       [[-1.74873434, -1.75211767, -0.42685525],
        [ 0.42949706,  0.03930767,  0.2911378 ]],

       [[-0.17188514,  0.09358439,  0.34600794],
        [ 0.45349848, -0.70797609,  0.53693337]]])

In [7]:
rd2 = np.random.randint(0, 100, 36).reshape(6, 6)
rd2

array([[45, 82, 62, 31, 59, 24],
       [73, 39, 49, 63, 95, 88],
       [99, 41, 56, 14, 50, 41],
       [93, 44, 21, 56, 85,  2],
       [ 8, 97,  6, 31, 35, 50],
       [ 2, 11, 66,  0, 87, 69]])